-- Run this entire script in Supabase:
-- SQL Editor > New query > paste > Run

create table if not exists public.contracts (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    date_saved timestamptz not null default now(),
    contract_name text not null,
    contract_type text not null,
    offer_group text,
    system_name text,
    total_payout numeric not null check (total_payout > 0),
    expenses numeric not null default 0 check (expenses >= 0),
    crew_members integer not null default 1 check (crew_members >= 1),
    net_payout numeric not null,
    individual_share numeric not null,
    notes text
);

create table if not exists public.ore_transactions (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    date_saved timestamptz not null default now(),
    action text not null check (action in ('Mined', 'Bought', 'Sold')),
    ore_name text not null,
    quantity_scu numeric not null default 0 check (quantity_scu >= 0),
    total_value numeric not null default 0 check (total_value >= 0),
    location text,
    notes text

);

-- Safe upgrades for existing deployments
alter table public.ore_transactions
    add column if not exists quantity_scu numeric not null default 0;

alter table public.ore_transactions
    drop constraint if exists ore_transactions_total_value_check;

alter table public.ore_transactions
    add constraint ore_transactions_total_value_check
    check (total_value >= 0);

alter table public.ore_transactions
    drop constraint if exists ore_transactions_quantity_scu_check;

alter table public.ore_transactions
    add constraint ore_transactions_quantity_scu_check
    check (quantity_scu >= 0);

create index if not exists contracts_user_id_idx
    on public.contracts(user_id);

create index if not exists contracts_date_saved_idx
    on public.contracts(date_saved desc);

create index if not exists ore_transactions_user_id_idx
    on public.ore_transactions(user_id);

create index if not exists ore_transactions_date_saved_idx
    on public.ore_transactions(date_saved desc);

alter table public.contracts enable row level security;
alter table public.ore_transactions enable row level security;

drop policy if exists "Users can read own contracts" on public.contracts;
drop policy if exists "Users can insert own contracts" on public.contracts;
drop policy if exists "Users can update own contracts" on public.contracts;
drop policy if exists "Users can delete own contracts" on public.contracts;

create policy "Users can read own contracts"
on public.contracts
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can insert own contracts"
on public.contracts
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update own contracts"
on public.contracts
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete own contracts"
on public.contracts
for delete
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can read own ore entries"
on public.ore_transactions;

drop policy if exists "Users can insert own ore entries"
on public.ore_transactions;

drop policy if exists "Users can update own ore entries"
on public.ore_transactions;

drop policy if exists "Users can delete own ore entries"
on public.ore_transactions;

create policy "Users can read own ore entries"
on public.ore_transactions
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can insert own ore entries"
on public.ore_transactions
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update own ore entries"
on public.ore_transactions
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete own ore entries"
on public.ore_transactions
for delete
to authenticated
using ((select auth.uid()) = user_id);
